### ISSUE TITLE
cant get your software working :(

### ISSUE THREAD

**Issue by tomasparks** [paulharter/blockmodel#1]
I am trying to load a schematic and save it as a X3D file
the usage instruction are incomplete

```
#!/usr/bin/env python2
import BlockModel
Block_Model = BlockModel.from_schematic_file("./test.schematic", max_size=None)
Block_Model.save_as_x3d("./test.x3d")
```

Traceback (most recent call last):
  File "./test.py", line 2, in <module>
    import BlockModel
ImportError: No module named BlockModel

```
#!/usr/bin/env python2
import blockmodel
Block_Model = blockmodel.from_schematic_file("./test.schematic", max_size=None)
Block_Model.save_as_x3d("./test.x3d")
```

Traceback (most recent call last):
  File "./test.py", line 3, in <module>
    Block_Model = blockmodel.from_schematic_file("./test.schematic", max_size=None)
AttributeError: 'module' object has no attribute 'from_schematic_file'

**Comment by paulharter** [comment]
try 

from blockmodel import BlockModel

model = BlockModel.from_schematic_file("./test.schematic", max_size=None)

This should work. 

blockmodel is the module, BlockModel is a class and from_schematic_file a classmethod on BlockModel

**Comment by tomasparks** [comment]
it works :)
