### ISSUE TITLE
blockmodel featured on twitter

### ISSUE THREAD

**Issue by tomasparks** [paulharter/blockmodel#2]
> New #Minecraft converter supports #X3D publishing using #X3DOM export. https://tomasparks.github.io/temp/minecraft2x3d/test_x3d.html … with discussion at http://web3d.org/pipermail/x3d-public_web3d.org/2016-September/005211.html …

https://twitter.com/Web3DConsortium/status/781876960553152512

**Comment by paulharter** [comment]
@tomasparks that's very cool. When I have time I'll change the previews on printcraft to use this instead of the current .obj in three.js which are a bit rubbish
