### ISSUE TITLE
3D model to schematic with texture

### ISSUE THREAD

**Issue by FuYang001** [paulharter/blockmodel#4]
Is it possible to import 3D model to schematic with texture?

**Comment by paulharter** [comment]
I’m afraid not. The schematic format doesn’t include textures, it just uses the textures available in the server for each block type.

You can however load different texture packs on the server to change how everything looks, but this will effect everything on the server. One possibility if you want a small number of different textures is to copy the default textures and replace a few seldom used textures with your custom ones.
